document.addEventListener('DOMContentLoaded',()=>{
  const type=document.body.dataset.calculator;if(!type||!window.GarageMathCore)return;
  const q=id=>document.getElementById(id),results=document.querySelector('[data-results]'),calcBtn=document.querySelector('[data-calculate]');
  const val=id=>q(id)?.value,n=id=>+val(id);let userRun=false;
  const meta={
    tire:{label:'Geometry calculation',next:'Verify the exact tire model’s published dimensions, load rating, wheel-width range and physical clearance.'},
    wheel:{label:'Geometry calculation',next:'Measure current strut and fender clearance, then check brake-spoke clearance and suspension travel.'},
    backspacing:{label:'Geometry estimate',next:'Measure the actual wheel from hub face to inner rim lip when clearance is tight.'},
    rpm:{label:'Theoretical drivetrain calculation',next:'Confirm actual transmission ratio, final-drive ratio and loaded tire diameter or revs per mile.'},
    fuel:{label:'Direct cost estimate',next:'Use real-world MPG from several fill-ups if you are budgeting an actual trip or annual cost.'},
    power:{label:'Direct ratio',next:'Compare vehicles using the same horsepower basis and the same weight convention.'},
    displacement:{label:'Geometry calculation',next:'Use finished bore and stroke measurements when the number matters for an engine build.'},
    compression:{label:'Geometry calculation',next:'Verify chamber, piston, gasket and deck volumes with measured values rather than catalog assumptions.'},
    quarter:{label:'Empirical estimate',next:'Treat this as a screening estimate only. Traction, weather, gearing and driver inputs can move the time slip substantially.'},
    injector:{label:'Planning estimate',next:'Verify injector flow at your pressure differential, fuel type, pump capacity and tuner requirements before buying parts.'}
  };
  function clearInvalid(){document.querySelectorAll('.calc [aria-invalid="true"]').forEach(el=>el.removeAttribute('aria-invalid'))}
  function fail(msg,ids=[]){clearInvalid();ids.forEach(id=>q(id)?.setAttribute('aria-invalid','true'));results.innerHTML=`<div class="error-box" role="alert">${msg}</div>`;results.dataset.lastSummary='';gmTrack('calculator_error',{calculator:type,fields:ids.join(',')});q(ids[0])?.focus()}
  function resultType(){return `<div class="result-type-row"><span class="result-type"><strong>${meta[type].label}</strong></span><a class="pill" href="methodology.html">Methodology</a></div>`}
  function setResults(items,summary,visual='',math=''){clearInvalid();results.innerHTML=resultType()+`<p class="result-summary">${summary}</p><div class="results-grid">${items.map(([label,value])=>`<div class="result"><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>${visual}${math?`<div class="math-work"><strong>Math with your numbers</strong><code>${math}</code></div>`:''}<div class="next-check"><strong>What to check next</strong><p>${meta[type].next}</p></div>`;results.dataset.lastSummary=`${document.title}\n${summary}\n`+items.map(([a,b])=>`${a}: ${b}`).join('\n')+'\n'+location.href}
  function syncUrl(){const p=new URLSearchParams();document.querySelectorAll('.calc input,.calc select').forEach(el=>{if(el.id&&el.value!=='')p.set(el.id,el.value)});history.replaceState(null,'',location.pathname+(p.toString()?`?${p}`:'')+location.hash)}
  function restoreUrl(){const p=new URLSearchParams(location.search);document.querySelectorAll('.calc input,.calc select').forEach(el=>{if(el.id&&p.has(el.id))el.value=p.get(el.id)})}
  function done(summary){if(userRun){syncUrl();gmTrack('calculator_completed',{calculator:type});saveRecent(summary)}return summary}
  function saveRecent(summary){try{const recent=JSON.parse(localStorage.getItem('gm_recent')||'[]');const inputs={};document.querySelectorAll('.calc input,.calc select').forEach(el=>{if(el.id)inputs[el.id]=el.value});const item={type,title:document.querySelector('h1')?.textContent||document.title,summary,url:location.pathname+location.search,inputs,ts:Date.now()};const next=[item,...recent.filter(r=>!(r.type===type&&JSON.stringify(r.inputs)===JSON.stringify(inputs)))].slice(0,8);localStorage.setItem('gm_recent',JSON.stringify(next))}catch{}}
  function applyActiveVehicle(){if(new URLSearchParams(location.search).toString())return;try{const id=localStorage.getItem('gm_active_vehicle');if(!id)return;const list=JSON.parse(localStorage.getItem('gm_vehicles')||'[]');const v=list.find(x=>x.id===id);if(!v)return;let used=false;if(type==='tire'&&v.tireSize&&q('old')){q('old').value=v.tireSize;used=true}if(type==='wheel'){if(v.wheelWidth&&q('w1')){q('w1').value=v.wheelWidth;used=true}if(v.wheelOffset!==''&&v.wheelOffset!=null&&q('o1'))q('o1').value=v.wheelOffset}if(type==='rpm'){if(v.finalDrive&&q('finaldrive')){q('finaldrive').value=v.finalDrive;used=true}if(v.tireSize&&q('dia')){const t=GarageMathCore.parseTire(v.tireSize);if(t){q('dia').value=t.diameter.toFixed(2);used=true}}}if(type==='power'||type==='quarter'){const hpId=type==='power'?'hp':'qhp',wtId=type==='power'?'weight':'qweight';if(v.horsepower&&q(hpId)){q(hpId).value=v.horsepower;used=true}if(v.weight&&q(wtId)){q(wtId).value=v.weight;used=true}}if(type==='injector'&&v.horsepower&&q('ihp')){q('ihp').value=v.horsepower;used=true}if(used){const box=document.querySelector('.calc>.panel:first-child');box?.insertAdjacentHTML('afterbegin',`<div class="vehicle-context">Using saved Garage vehicle: <strong>${escapeHtml(v.name||'Vehicle')}</strong>. <a href="garage.html">Manage Garage</a></div>`)}}catch{}}
  function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
  function addHints(){const hints={o1:'Positive offset generally moves the wheel inward. Negative offset moves it outward.',o2:'Compare this with the current wheel, not in isolation.',bo:'Offset is in millimeters; backspacing is returned in inches.',gear:'Use the ratio of the actual transmission gear selected.',finaldrive:'Axle or differential final-drive ratio.',piston:'Dish volume is positive; dome volume is negative in this calculator.',bsfc:'Brake-specific fuel consumption is a planning assumption, not a measured injector property.',duty:'Maximum commanded injector on-time as a percentage of the cycle.',qweight:'Use race weight if comparing to a time slip, including driver and fuel if appropriate.',weight:'Use the same weight convention when comparing vehicles.'};Object.entries(hints).forEach(([id,text])=>{const el=q(id);if(el&&!el.parentElement.querySelector('.field-help'))el.insertAdjacentHTML('afterend',`<small class="field-help">${text}</small>`)})}
  function addPresets(){const panel=document.querySelector('.calc>.panel:first-child');if(!panel||panel.querySelector('.preset-bar'))return;const sets={
    tire:[['Street example',{old:'225/45R17',new:'245/40R18',mph:'60'}],['Truck example',{old:'275/55R20',new:'285/70R17',mph:'60'}]],
    rpm:[['3.55 axle',{finaldrive:'3.55'}],['3.73 axle',{finaldrive:'3.73'}],['4.10 axle',{finaldrive:'4.10'}]],
    injector:[['4 injectors',{injectors:'4'}],['6 injectors',{injectors:'6'}],['8 injectors',{injectors:'8'}]],
    power:[['Example: 400 hp / 3600 lb',{hp:'400',weight:'3600'}]],
    quarter:[['Example: 500 hp / 3600 lb',{qhp:'500',qweight:'3600'}]]
  };if(!sets[type])return;const html=`<div class="preset-bar"><span class="preset-label">Quick examples / presets</span><div class="preset-actions">${sets[type].map((x,i)=>`<button type="button" data-preset-index="${i}">${x[0]}</button>`).join('')}</div></div>`;calcBtn.insertAdjacentHTML('beforebegin',html);panel.querySelectorAll('[data-preset-index]').forEach(b=>b.addEventListener('click',()=>{const values=sets[type][+b.dataset.presetIndex][1];Object.entries(values).forEach(([id,v])=>{if(q(id))q(id).value=v});f[type]?.();gmTrack('calculator_preset_used',{calculator:type,preset:+b.dataset.presetIndex})}))}
  function tireVisual(r){const base=118,ratio=r.new.diameter/r.old.diameter,newSize=Math.max(92,Math.min(148,base*ratio));return `<div class="calc-visual"><div class="calc-visual-title"><span>Visual comparison</span><span>Nominal diameter</span></div><div class="tire-viz"><div class="tire-viz-col"><div class="tire-ring" style="--size:${base}px"><span>${num(r.old.diameter,2)}&quot;</span></div><small>${escapeHtml(val('old'))}</small></div><div class="tire-viz-col"><div class="tire-ring new" style="--size:${newSize}px"><span>${num(r.new.diameter,2)}&quot;</span></div><small>${escapeHtml(val('new'))}</small></div></div></div>`}
  function wheelVisual(){const oldW=n('w1')*25.4,newW=n('w2')*25.4,oldInner=-(oldW/2+n('o1')),oldOuter=oldW/2-n('o1'),newInner=-(newW/2+n('o2')),newOuter=newW/2-n('o2'),low=Math.min(oldInner,newInner,0),high=Math.max(oldOuter,newOuter,0),pad=(high-low)*.12+8,min=low-pad,max=high+pad,map=x=>5+90*((x-min)/(max-min)),oldL=map(oldInner),oldR=map(oldOuter),newL=map(newInner),newR=map(newOuter),hub=map(0);return `<div class="calc-visual"><div class="calc-visual-title"><span>Wheel position</span><span>Hub face reference</span></div><div class="wheel-viz"><div class="wheel-track"><div class="wheel-hub-line" style="--hub:${hub}%"></div><div class="wheel-bar current" style="--left:${oldL}%;--width:${oldR-oldL}%"><span>Current</span></div><div class="wheel-bar new" style="--left:${newL}%;--width:${newR-newL}%"><span>New</span></div></div><div class="wheel-labels"><span>← suspension</span><span>fender →</span></div></div></div>`}
  function rpmVisual(r){return `<div class="calc-visual"><div class="calc-visual-title"><span>Gearing snapshot</span><span>Theoretical</span></div><div class="speed-strip"><div class="speed-node"><strong>${num(n('rpm'),0)} RPM</strong><span>entered engine speed</span></div><div class="speed-arrow">→</div><div class="speed-node"><strong>${num(r.mph,1)} mph</strong><span>calculated road speed</span></div></div><div class="ratio-callout"><span>At ${num(n('targetmph'),0)} mph</span><strong>${num(r.requiredRpm,0)} RPM</strong></div></div>`}
  function compressionVisual(r){const total=r.sweptCc+r.clearanceCc,sweptPct=r.sweptCc/total*100,clearPct=r.clearanceCc/total*100;return `<div class="calc-visual"><div class="calc-visual-title"><span>Volume budget</span><span>One cylinder</span></div><div class="volume-bar"><div class="volume-swept" style="width:${sweptPct}%"><span>Swept</span></div><div class="volume-clearance" style="width:${clearPct}%"><span>Clearance</span></div></div><div class="ratio-callout"><span>${num(r.sweptCc,1)} cc + ${num(r.clearanceCc,1)} cc</span><strong>${num(r.ratio,2)}:1</strong></div></div>`}
  function backspacingVisual(r){const fill=Math.max(10,Math.min(90,r.nominal/(n('bw')+1)*100));return `<div class="calc-visual"><div class="calc-visual-title"><span>Backspacing position</span><span>Nominal geometry</span></div><div class="simple-gauge"><span style="--fill:${fill}%"></span></div><div class="gauge-labels"><span>outer lip</span><span>hub face at ${num(r.nominal,2)} in</span><span>inner lip</span></div></div>`}
  function fuelVisual(r){const annualMonthly=r.annualCost/12;return `<div class="calc-visual"><div class="calc-visual-title"><span>Fuel budget snapshot</span><span>Your assumptions</span></div><div class="speed-strip"><div class="speed-node"><strong>${money(r.cost)}</strong><span>${num(n('distance'),0)} mile trip</span></div><div class="speed-arrow">→</div><div class="speed-node"><strong>${money(annualMonthly)}/mo</strong><span>annual estimate ÷ 12</span></div></div></div>`}
  function powerVisual(r){const fill=Math.max(8,Math.min(100,120/r.lbPerHp*10));return `<div class="calc-visual"><div class="calc-visual-title"><span>Power-to-weight snapshot</span><span>Lower lb/hp = less mass per hp</span></div><div class="simple-gauge"><span style="--fill:${fill}%"></span></div><div class="ratio-callout"><span>${num(n('weight'),0)} lb ÷ ${num(n('hp'),0)} hp</span><strong>${num(r.lbPerHp,2)} lb/hp</strong></div></div>`}
  function displacementVisual(r){const count=Math.max(1,Math.min(12,Math.round(n('cyl')))),h=Math.max(42,Math.min(105,r.perCylinderCi/60*105));return `<div class="calc-visual"><div class="calc-visual-title"><span>Cylinder volume</span><span>${count} cylinders</span></div><div class="cylinder-viz">${Array.from({length:count},()=>`<span class="cyl" style="--h:${h}px"></span>`).join('')}</div><div class="ratio-callout"><span>${num(r.perCylinderCi,2)} cu in each</span><strong>${num(r.totalCi,1)} cu in total</strong></div></div>`}
  function quarterVisual(r){const pct=Math.max(8,Math.min(86,100-r.et*4));return `<div class="calc-visual"><div class="calc-visual-title"><span>Quarter-mile estimate</span><span>Empirical shortcut</span></div><div class="track-viz"><span class="track-car" style="left:${pct}%"></span></div><div class="ratio-callout"><span>${num(r.et,2)} sec</span><strong>${num(r.trapMph,1)} mph</strong></div></div>`}
  function injectorVisual(r){const duty=Math.max(0,Math.min(100,n('duty')));return `<div class="calc-visual"><div class="calc-visual-title"><span>Injector headroom</span><span>Configured max duty</span></div><div class="simple-gauge"><span style="--fill:${duty}%"></span></div><div class="gauge-labels"><span>0%</span><span>${num(duty,0)}% max commanded duty</span><span>100%</span></div><div class="ratio-callout"><span>${n('injectors')} injectors</span><strong>${num(r.lbHr,1)} lb/hr each</strong></div></div>`}
  const f={
    tire(){try{if(!GarageMathCore.parseTire(val('old'))||!GarageMathCore.parseTire(val('new'))||n('mph')<0)return fail('Use tire sizes such as 225/45R17 and a non-negative speed.',['old','new']);const r=GarageMathCore.tireCompare(val('old'),val('new'),n('mph')),direction=r.diameterPct>=0?'taller':'shorter',oldSide=r.old.width*(r.old.aspect/100)/25.4,newSide=r.new.width*(r.new.aspect/100)/25.4;setResults([['Current diameter',`${num(r.old.diameter,2)} in`],['New diameter',`${num(r.new.diameter,2)} in`],['Diameter change',`${r.diameterPct>=0?'+':''}${num(r.diameterPct,2)}%`],['Ride-height change',`${r.rideHeight>=0?'+':''}${num(r.rideHeight,2)} in`],['Actual speed',`${num(r.actualMph,1)} mph`]],done(`The new tire is ${num(Math.abs(r.diameterPct),2)}% ${direction}. At ${num(n('mph'),0)} mph indicated, geometric road speed is about ${num(r.actualMph,1)} mph if the original calibration was accurate.`),tireVisual(r),`${r.old.width} × ${r.old.aspect/100} ÷ 25.4 = ${num(oldSide,2)} in sidewall; diameter = ${r.old.rim} + 2 × ${num(oldSide,2)} = ${num(r.old.diameter,2)} in. New sidewall = ${num(newSide,2)} in; new diameter = ${num(r.new.diameter,2)} in.`)}catch{return fail('Use tire sizes such as 225/45R17 and a valid speed.',['old','new'])}},
    wheel(){if(n('w1')<=0||n('w2')<=0||!Number.isFinite(n('o1'))||!Number.isFinite(n('o2')))return fail('Enter positive wheel widths and valid offsets.',['w1','w2']);const r=GarageMathCore.wheelOffsetCompare(n('w1'),n('o1'),n('w2'),n('o2')),inner=r.innerClearanceChange>=0?`${num(r.innerClearanceChange,1)} mm more clearance`:`${num(Math.abs(r.innerClearanceChange),1)} mm less clearance`,outer=r.outerPokeChange>=0?`${num(r.outerPokeChange,1)} mm farther outward`:`${num(Math.abs(r.outerPokeChange),1)} mm farther inward`;setResults([['Suspension-side change',inner],['Fender-side change',outer],['Width change',`${num(r.widthChangeIn,2)} in`]],done(`Compared with the current wheel, the new wheel has ${inner.toLowerCase()} on the suspension side and sits ${outer.toLowerCase()} on the fender side.`),wheelVisual(),`Current half-width = ${n('w1')} × 25.4 ÷ 2 = ${num(n('w1')*12.7,1)} mm. New half-width = ${n('w2')} × 25.4 ÷ 2 = ${num(n('w2')*12.7,1)} mm. Offset is then applied to both inner and outer wheel-edge positions.`)},
    backspacing(){if(n('bw')<=0||!Number.isFinite(n('bo')))return fail('Enter a positive wheel width and a valid offset.',['bw','bo']);const r=GarageMathCore.backspacing(n('bw'),n('bo'));setResults([['Nominal backspacing',`${num(r.nominal,2)} in`],['Approx. lip-adjusted',`${num(r.lipAdjusted,2)} in`],['Offset',`${n('bo')>=0?'+':''}${num(n('bo'),0)} mm`]],done(`Nominal backspacing is ${num(r.nominal,2)} inches. The lip-adjusted estimate is ${num(r.lipAdjusted,2)} inches; manufacturer-measured backspacing is preferred when clearance is tight.`),backspacingVisual(r),`${n('bw')} ÷ 2 + (${n('bo')} ÷ 25.4) = ${num(r.nominal,2)} in nominal backspacing.`)},
    rpm(){if(n('rpm')<0||n('dia')<=0||n('gear')<=0||n('finaldrive')<=0||n('targetmph')<0)return fail('RPM and target speed must be non-negative; tire diameter and ratios must be above zero.',['dia','gear','finaldrive']);const r=GarageMathCore.rpmSpeed(n('rpm'),n('dia'),n('gear'),n('finaldrive'),n('targetmph'));setResults([['Speed at entered RPM',`${num(r.mph,1)} mph`],['RPM at target speed',`${num(r.requiredRpm,0)} RPM`],['Overall ratio',`${num(r.overallRatio,3)}:1`]],done(`Theoretical road speed is ${num(r.mph,1)} mph at ${num(n('rpm'),0)} RPM. At ${num(n('targetmph'),0)} mph the same gearing calculates to about ${num(r.requiredRpm,0)} RPM.`),rpmVisual(r),`${num(n('rpm'),0)} × ${num(n('dia'),2)} ÷ (${n('gear')} × ${n('finaldrive')} × 336) = ${num(r.mph,1)} mph.`)},
    fuel(){if(n('distance')<0||n('mpg')<=0||n('price')<0||n('annual')<0)return fail('Distance, fuel price and annual miles must be non-negative; MPG must be above zero.',['mpg']);const r=GarageMathCore.fuelCost(n('distance'),n('mpg'),n('price'),n('annual'));setResults([['Trip fuel',`${num(r.gallons,2)} gal`],['Trip cost',money(r.cost)],['Cost per mile',money(r.costPerMile)],['Annual fuel',`${num(r.annualGallons,0)} gal`],['Estimated annual cost',money(r.annualCost)]],done(`At ${num(n('mpg'),1)} MPG and ${money(n('price'))}/gal, this trip is estimated at ${money(r.cost)} in fuel and ${money(r.costPerMile)} per mile.`),fuelVisual(r),`${num(n('distance'),0)} miles ÷ ${num(n('mpg'),1)} MPG = ${num(r.gallons,2)} gal; ${num(r.gallons,2)} × ${money(n('price'))} = ${money(r.cost)}.`)},
    power(){if(n('hp')<=0||n('weight')<=0)return fail('Enter horsepower and vehicle weight above zero.',['hp','weight']);const r=GarageMathCore.powerToWeight(n('hp'),n('weight'));setResults([['Pounds per horsepower',`${num(r.lbPerHp,2)} lb/hp`],['Horsepower per US ton',`${num(r.hpPerTon,1)} hp/ton`],['Horsepower per 1,000 lb',`${num(r.hpPer1000,1)} hp`]],done(`This combination works out to ${num(r.lbPerHp,2)} pounds per horsepower. Use the same horsepower basis and vehicle-weight convention when comparing vehicles.`),powerVisual(r),`${num(n('weight'),0)} lb ÷ ${num(n('hp'),0)} hp = ${num(r.lbPerHp,2)} lb/hp.`)},
    displacement(){if(n('bore')<=0||n('stroke')<=0||n('cyl')<=0)return fail('Enter bore, stroke and cylinder count above zero.',['bore','stroke','cyl']);const r=GarageMathCore.displacement(n('bore'),n('stroke'),n('cyl'));setResults([['Total displacement',`${num(r.totalCi,1)} cu in`],['Metric displacement',`${num(r.totalCc,0)} cc`],['Liters',`${num(r.liters,2)} L`],['Per cylinder',`${num(r.perCylinderCi,2)} cu in`]],done(`The entered bore, stroke and cylinder count produce approximately ${num(r.totalCi,1)} cubic inches, or ${num(r.liters,2)} liters, of swept volume.`),displacementVisual(r),`π ÷ 4 × ${n('bore')}² × ${n('stroke')} = ${num(r.perCylinderCi,2)} cu in per cylinder; × ${n('cyl')} = ${num(r.totalCi,1)} cu in.`)},
    compression(){try{if(n('cbore')<=0||n('cstroke')<=0||n('chamber')<=0||n('gbore')<=0||n('gthick')<0||n('deck')<0)return fail('Enter valid positive engine dimensions; gasket thickness and deck clearance cannot be negative.',['cbore','cstroke','chamber','gbore']);const r=GarageMathCore.compressionRatio(n('cbore'),n('cstroke'),n('chamber'),n('piston'),n('gbore'),n('gthick'),n('deck'));setResults([['Static compression ratio',`${num(r.ratio,2)}:1`],['Swept volume / cylinder',`${num(r.sweptCc,1)} cc`],['Clearance volume',`${num(r.clearanceCc,1)} cc`],['Gasket volume',`${num(r.gasketCc,1)} cc`],['Deck volume',`${num(r.deckCc,1)} cc`]],done(`The entered geometry produces a static compression ratio of approximately ${num(r.ratio,2)}:1. Small chamber, gasket, piston or deck measurement errors can materially change the result.`),compressionVisual(r),`(${num(r.sweptCc,1)} cc swept + ${num(r.clearanceCc,1)} cc clearance) ÷ ${num(r.clearanceCc,1)} cc = ${num(r.ratio,2)}:1.`)}catch(e){fail(e.message||'Check the engine dimensions.',['chamber'])}},
    quarter(){if(n('qhp')<=0||n('qweight')<=0)return fail('Enter horsepower and race weight above zero.',['qhp','qweight']);const r=GarageMathCore.quarterMile(n('qhp'),n('qweight'));setResults([['Estimated quarter-mile ET',`${num(r.et,2)} sec`],['Estimated trap speed',`${num(r.trapMph,1)} mph`],['Power-to-weight',`${num(r.lbPerHp,2)} lb/hp`]],done(`The empirical weight-to-power shortcut estimates about ${num(r.et,2)} seconds at ${num(r.trapMph,1)} mph. Real results can move significantly with traction, weather, gearing and driving.`),quarterVisual(r),`ET ≈ 5.825 × ∛(${num(n('qweight'),0)} ÷ ${num(n('qhp'),0)}) = ${num(r.et,2)} sec. Trap ≈ 234 × ∛(${num(n('qhp'),0)} ÷ ${num(n('qweight'),0)}) = ${num(r.trapMph,1)} mph.`)},
    injector(){if(n('ihp')<=0||n('bsfc')<=0||n('injectors')<=0||n('duty')<=0||n('duty')>100)return fail('Horsepower, BSFC and injector count must be above zero; duty cycle must be between 1% and 100%.',['ihp','bsfc','injectors','duty']);const r=GarageMathCore.injectorSize(n('ihp'),n('bsfc'),n('injectors'),n('duty'));setResults([['Required injector flow',`${num(r.lbHr,1)} lb/hr each`],['Approx. gasoline flow',`${num(r.ccMinApprox,0)} cc/min each`],['Total fuel mass flow',`${num(r.totalLbHr,1)} lb/hr`]],done(`Using the entered BSFC and duty-cycle assumptions, the planning minimum is about ${num(r.lbHr,1)} lb/hr per injector. Verify manufacturer flow data, pressure differential and fuel properties before selecting hardware.`),injectorVisual(r),`${num(n('ihp'),0)} hp × ${n('bsfc')} BSFC ÷ (${n('injectors')} injectors × ${num(n('duty')/100,2)} duty) = ${num(r.lbHr,1)} lb/hr each.`)}
  };
  restoreUrl();applyActiveVehicle();addHints();addPresets();
  calcBtn?.addEventListener('click',()=>{userRun=true;gmTrack('calculator_started',{calculator:type});f[type]?.();userRun=false});
  f[type]?.();
});
