document.addEventListener('DOMContentLoaded',()=>{
  const VEH='gm_vehicles',ACTIVE='gm_active_vehicle',REC='gm_recent';
  const form=document.getElementById('vehicle-form'),listEl=document.getElementById('garage-list'),recentEl=document.getElementById('recent-list');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const getVehicles=()=>{try{return JSON.parse(localStorage.getItem(VEH)||'[]')}catch{return[]}};
  const saveVehicles=v=>localStorage.setItem(VEH,JSON.stringify(v));
  const withParams=(page,params)=>{const p=new URLSearchParams();Object.entries(params).forEach(([k,v])=>{if(v!==''&&v!=null)p.set(k,v)});return p.toString()?`${page}?${p}`:page};
  function diameter(size){try{return window.GarageMathCore?.parseTire(size)?.diameter||''}catch{return''}}
  function links(v){const d=diameter(v.tireSize);return [[withParams('tire-size.html',{old:v.tireSize}),'Tire Size'],[withParams('rpm-speed.html',{dia:d?d.toFixed(2):'',finaldrive:v.finalDrive}),'RPM & Speed'],[withParams('hp-weight.html',{hp:v.horsepower,weight:v.weight}),'Power-to-Weight'],[withParams('wheel-offset.html',{w1:v.wheelWidth,o1:v.wheelOffset}),'Wheel Offset']]}
  function render(){const vehicles=getVehicles(),active=localStorage.getItem(ACTIVE);listEl.innerHTML=vehicles.length?vehicles.map(v=>`<article class="garage-card ${v.id===active?'is-active':''}" data-id="${esc(v.id)}"><strong>${esc(v.name||'Vehicle')}</strong><span>${[v.tireSize&&`Tire ${v.tireSize}`,v.weight&&`${v.weight} lb`,v.horsepower&&`${v.horsepower} hp`,v.finalDrive&&`${v.finalDrive}:1 final`,v.wheelWidth&&`${v.wheelWidth} in wheel`,v.wheelOffset!==''&&v.wheelOffset!=null&&`ET${v.wheelOffset}`].filter(Boolean).join(' · ')||'No specs saved yet'}</span><div class="garage-card-actions">${links(v).map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}<button type="button" data-action="active">${v.id===active?'Active vehicle':'Set active'}</button><button type="button" data-action="edit">Edit</button><button type="button" data-action="delete">Delete</button></div></article>`).join(''):'<p class="garage-empty">No vehicles saved yet. Add one to prefill compatible calculators.</p>';
    let rec=[];try{rec=JSON.parse(localStorage.getItem(REC)||'[]')}catch{}recentEl.innerHTML=rec.length?rec.map(r=>`<a class="garage-card" href="${esc(r.url||'#')}"><strong>${esc(r.title||'Recent calculation')}</strong><span>${esc(new Date(r.ts||Date.now()).toLocaleString())} · ${esc((r.summary||'').slice(0,150))}</span></a>`).join(''):'<p class="garage-empty">No recent calculations yet.</p>'}
  function values(){return{id:document.getElementById('vehicle-id').value||crypto.randomUUID?.()||String(Date.now()),name:document.getElementById('vehicle-name').value.trim(),tireSize:document.getElementById('vehicle-tire').value.trim(),weight:document.getElementById('vehicle-weight').value,horsepower:document.getElementById('vehicle-hp').value,finalDrive:document.getElementById('vehicle-final').value,wheelWidth:document.getElementById('vehicle-wheel-width').value,wheelOffset:document.getElementById('vehicle-wheel-offset').value}}
  form.addEventListener('submit',e=>{e.preventDefault();const v=values();if(!v.name){document.getElementById('vehicle-name').focus();return}const arr=getVehicles(),i=arr.findIndex(x=>x.id===v.id);if(i>=0)arr[i]=v;else arr.unshift(v);saveVehicles(arr);if(!localStorage.getItem(ACTIVE))localStorage.setItem(ACTIVE,v.id);form.reset();document.getElementById('vehicle-id').value='';render();gmTrack('garage_vehicle_saved',{})});
  listEl.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;const card=btn.closest('[data-id]'),id=card?.dataset.id,arr=getVehicles(),v=arr.find(x=>x.id===id);if(!v)return;if(btn.dataset.action==='active'){localStorage.setItem(ACTIVE,id);gmTrack('garage_vehicle_activated',{});render()}if(btn.dataset.action==='delete'){if(confirm(`Delete ${v.name||'this vehicle'} from this device?`)){saveVehicles(arr.filter(x=>x.id!==id));if(localStorage.getItem(ACTIVE)===id)localStorage.removeItem(ACTIVE);render();gmTrack('garage_vehicle_deleted',{})}}if(btn.dataset.action==='edit'){document.getElementById('vehicle-id').value=v.id;document.getElementById('vehicle-name').value=v.name||'';document.getElementById('vehicle-tire').value=v.tireSize||'';document.getElementById('vehicle-weight').value=v.weight||'';document.getElementById('vehicle-hp').value=v.horsepower||'';document.getElementById('vehicle-final').value=v.finalDrive||'';document.getElementById('vehicle-wheel-width').value=v.wheelWidth||'';document.getElementById('vehicle-wheel-offset').value=v.wheelOffset??'';form.scrollIntoView({behavior:'smooth',block:'start'})}});
  document.getElementById('clear-recents').addEventListener('click',()=>{localStorage.removeItem(REC);render()});render();
});
